sudo: required
services:
  - docker

before_install:
  - docker build -t ci/test  -f  ./client/Dockerfile.dev ./client

script:
  - docker run ci/test npm  test -- --coverage

after_success:
  - docker build -t danish903/client ./client
  - docker build -t danish903/nginx ./nginx
  - docker build -t danish903/server ./server
  - docker build -t danish903/worker ./worker

  - echo "$DOCK_PASS" | docker login -u "$DOCK_ID" --password-stdin

  - docker push danish903/client
  - docker push danish903/nginx
  - docker push danish903/server
  - docker push danish903/worker
